name: Create Google Apps Script Release

on:
  release:
    types: [published]

jobs:
  build-and-release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Archive Translations
        id: archive_translations # 为此步骤添加ID
        run: |
          # 检查 translations 目录是否存在
          if [ -d "translations" ]; then
            cd translations # 进入目录
            zip -r ../translations.zip ./* # 打包当前目录所有内容到上级目录
            cd .. # 返回上级目录
            echo "Generated translations.zip"
            ls -l translations.zip
            echo "::set-output name=zip_created::true" # 设置一个输出，表示文件已创建
          else
            echo "translations directory not found, skipping zip creation."
            echo "::set-output name=zip_created::false" # 设置输出，表示文件未创建
          fi

      - name: Upload Translations Asset
        # 仅当 translations.zip 被成功创建时才上传
        if: steps.archive_translations.outputs.zip_created == 'true'
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: ./translations.zip
          asset_name: translations.zip
          asset_content_type: application/zip


